// components/ClientViewModal.tsx
import { X, User, Mail, Phone, MapPin, Globe, Calendar, FileText, Download, Share2 } from 'lucide-react';

interface ClientDetails {
  id: string;
  full_name: string;
  email: string;
  phone: string;
  address: string;
  passport_number: string;
  passport_expiry: string;
  nationality: string;
  emergency_contact_name: string;
  emergency_contact_phone: string;
  passport_image_url?: string;
  created_at: string;
}

interface ClientViewModalProps {
  client: ClientDetails | null;
  isOpen: boolean;
  onClose: () => void;
}

export function ClientViewModal({ client, isOpen, onClose }: ClientViewModalProps) {
  if (!isOpen || !client) return null;

  const downloadClientDetails = () => {
    const content = `
CLIENT DETAILS - TULI TRAVEL
============================

Personal Information:
--------------------
Full Name: ${client.full_name}
Email: ${client.email}
Phone: ${client.phone}
Address: ${client.address}
Nationality: ${client.nationality}

Passport Details:
----------------
Passport Number: ${client.passport_number}
Expiry Date: ${client.passport_expiry}
${client.passport_image_url ? 'Passport Photo: Uploaded' : 'Passport Photo: Not uploaded'}

Emergency Contact:
-----------------
Name: ${client.emergency_contact_name}
Phone: ${client.emergency_contact_phone}

Date Added: ${new Date(client.created_at).toLocaleDateString()}
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `client-${client.full_name.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const shareClientDetails = () => {
    const message = `📋 Client Details - Tuli Travel

Personal Information:
• Full Name: ${client.full_name}
• Email: ${client.email}
• Phone: ${client.phone}
• Address: ${client.address}
• Nationality: ${client.nationality}

Passport Details:
• Passport Number: ${client.passport_number}
• Expiry Date: ${new Date(client.passport_expiry).toLocaleDateString()}

Emergency Contact:
• Name: ${client.emergency_contact_name}
• Phone: ${client.emergency_contact_phone}

Generated by Tuli Travel System`;

    const encodedMessage = encodeURIComponent(message);
    const whatsappUrl = `https://wa.me/?text=${encodedMessage}`;
    window.open(whatsappUrl, '_blank');
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-4xl max-h-[90vh] overflow-hidden">
        {/* Header */}
        <div className="flex justify-between items-center p-6 border-b border-slate-200">
          <h3 className="text-lg font-semibold text-slate-900">Client Details</h3>
          <button 
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600 transition-colors p-1 rounded-lg"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-auto max-h-[calc(90vh-120px)]">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Personal Information */}
            <div className="space-y-6">
              <div>
                <h4 className="text-sm font-semibold text-slate-500 uppercase mb-4 flex items-center gap-2">
                  <User className="w-4 h-4" />
                  Personal Information
                </h4>
                <div className="space-y-4">
                  <div>
                    <label className="text-xs font-semibold text-slate-500">Full Name</label>
                    <p className="text-sm text-slate-900 font-semibold mt-1">{client.full_name}</p>
                  </div>
                  <div className="grid grid-cols-1 gap-4">
                    <div>
                      <label className="text-xs font-semibold text-slate-500 flex items-center gap-1">
                        <Mail className="w-3 h-3" />
                        Email Address
                      </label>
                      <p className="text-sm text-slate-900 mt-1">{client.email}</p>
                    </div>
                    <div>
                      <label className="text-xs font-semibold text-slate-500 flex items-center gap-1">
                        <Phone className="w-3 h-3" />
                        Phone Number
                      </label>
                      <p className="text-sm text-slate-900 mt-1">{client.phone}</p>
                    </div>
                  </div>
                  <div>
                    <label className="text-xs font-semibold text-slate-500 flex items-center gap-1">
                      <MapPin className="w-3 h-3" />
                      Address
                    </label>
                    <p className="text-sm text-slate-900 mt-1 whitespace-pre-wrap">{client.address}</p>
                  </div>
                  <div>
                    <label className="text-xs font-semibold text-slate-500 flex items-center gap-1">
                      <Globe className="w-3 h-3" />
                      Nationality
                    </label>
                    <p className="text-sm text-slate-900 mt-1">{client.nationality}</p>
                  </div>
                </div>
              </div>

              {/* Emergency Contact */}
              <div>
                <h4 className="text-sm font-semibold text-slate-500 uppercase mb-4">Emergency Contact</h4>
                <div className="space-y-3">
                  <div>
                    <label className="text-xs font-semibold text-slate-500">Contact Name</label>
                    <p className="text-sm text-slate-900 font-semibold mt-1">{client.emergency_contact_name}</p>
                  </div>
                  <div>
                    <label className="text-xs font-semibold text-slate-500">Contact Phone</label>
                    <p className="text-sm text-slate-900 font-semibold mt-1">{client.emergency_contact_phone}</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Passport Information */}
            <div className="space-y-6">
              <div>
                <h4 className="text-sm font-semibold text-slate-500 uppercase mb-4 flex items-center gap-2">
                  <FileText className="w-4 h-4" />
                  Passport Details
                </h4>
                <div className="space-y-4">
                  <div>
                    <label className="text-xs font-semibold text-slate-500">Passport Number</label>
                    <p className="text-sm text-slate-900 font-semibold mt-1 font-mono">{client.passport_number}</p>
                  </div>
                  <div>
                    <label className="text-xs font-semibold text-slate-500 flex items-center gap-1">
                      <Calendar className="w-3 h-3" />
                      Expiry Date
                    </label>
                    <p className="text-sm text-slate-900 mt-1">
                      {new Date(client.passport_expiry).toLocaleDateString()}
                    </p>
                  </div>
                  <div>
                    <label className="text-xs font-semibold text-slate-500">Passport Photo</label>
                    <div className="mt-2">
                      {client.passport_image_url ? (
                        <div className="space-y-2">
                          <img 
                            src={client.passport_image_url} 
                            alt="Passport" 
                            className="w-32 h-32 object-cover rounded-lg border border-slate-200"
                          />
                          <a 
                            href={client.passport_image_url} 
                            target="_blank" 
                            rel="noopener noreferrer"
                            className="text-blue-600 hover:text-blue-700 text-sm font-semibold"
                          >
                            View Full Image
                          </a>
                        </div>
                      ) : (
                        <p className="text-sm text-slate-500 italic">No passport photo uploaded</p>
                      )}
                    </div>
                  </div>
                </div>
              </div>

              {/* Metadata */}
              <div className="bg-slate-50 rounded-xl p-4">
                <h4 className="text-sm font-semibold text-slate-500 uppercase mb-3">Record Information</h4>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span className="text-slate-600">Date Added:</span>
                    <span className="text-slate-900 font-semibold">
                      {new Date(client.created_at).toLocaleDateString()}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600">Client ID:</span>
                    <span className="text-slate-900 font-mono text-xs">{client.id}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="border-t border-slate-200 bg-slate-50 px-6 py-4">
          <div className="flex gap-3">
            <button
              onClick={downloadClientDetails}
              className="flex items-center gap-2 bg-white hover:bg-slate-100 text-slate-700 px-4 py-2 rounded-lg font-semibold transition-all text-sm border border-slate-300"
            >
              <Download className="w-4 h-4" />
              Download
            </button>
            <button
              onClick={shareClientDetails}
              className="flex items-center gap-2 bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded-lg font-semibold transition-all text-sm"
            >
              <Share2 className="w-4 h-4" />
              Share via WhatsApp
            </button>
            <button
              onClick={onClose}
              className="flex items-center gap-2 bg-slate-500 hover:bg-slate-600 text-white px-4 py-2 rounded-lg font-semibold transition-all text-sm ml-auto"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}